production:
  refresh_channel_sul_dlss:
    class: FetchChannelJob
    args: [ { channel_id: 'UCc2CQuHkhKGZ-2ZLTZVGE2A' } ]
    schedule: every tuesday at 5am
  refresh_channel_sul:
    class: FetchChannelJob
    args: [ { channel_id: 'UCw2hOU13JoFwWz9V4IztPrg' } ]
    schedule: every wednesday at 5am
  refresh_channel_rumsey:
    class: FetchChannelJob
    args: [ { channel_id: 'UC9haNAEghTn4pHPsQdDIG3A' } ]
    schedule: every thursday at 5am
  channel_report_sul_dlss:
    class: ChannelReportJob
    args: [ { channel_id: 'UCc2CQuHkhKGZ-2ZLTZVGE2A' } ]
    schedule: every friday at 5am
  channel_report_sul:
    class: ChannelReportJob
    args: [ { channel_id: 'UCw2hOU13JoFwWz9V4IztPrg' } ]
    schedule: every friday at 5am
  channel_report_rumsey:
    class: ChannelReportJob
    args: [ { channel_id: 'UC9haNAEghTn4pHPsQdDIG3A' } ]
    schedule: every friday at 5am
