http_headers:
  user_groups: 'X-Groups'
  first_name: 'X-Person-Name'
  full_name: 'X-Person-Formal-Name'
  remote_user: 'X-Remote-User'

reports:
  base_path: 'storage/reports'

# mappings from authorization role to workgroup name
authorization_workgroup_names:
  administrators: 'dlss:hydrus-app-administrators'
